[package]
name = "bubshurb/throttleutil"
description = "A simple utility module which implements a similar functionality of Matter.useThrottle."
authors = ["bubshurb"]
version = "1.0.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"