[package]
name = "bubshurb/playercacheutil"
description = "A very simple utility module for storing in data per player in an unique way."
authors = ["bubshurb"]
version = "1.1.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"