[package]
name = "bubshurb/instancereplicationutil"
description = "An utility module for working with instance replication."
authors = ["bubshurb"]
license = "MIT"
version = "1.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4"