[package]
name = "bubshurb/clientidlestatusutil"
description = "A simple utility module around the [Player.Idled](https://create.roblox.com/docs/reference/engine/classes/Player#Idled) event."
version = "1.0.0"
license = "MIT"
authors = ["bubshurb"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Property = "bubshurb/property@2"