[package]
name = "bubshurb/toolutil"
description = "A simple utility module for working with tools.."
authors = ["bubshurb"]
version = "1.2.4"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
playersUtil = "bubshurb/playersutil@1"
playerEventsUtil = "bubshurb/playereventsutil@1"