[package]
name = "bubshurb/instancetrackerutil"
description = "A simple utility module for working with instances and their properties."
authors = ["bubshurb"]
license = "MIT"
version = "1.2.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Property = "bubshurb/property@2"