[package]
name = "bubshurb/instancetagutil"
description = "A utility module for working with instance tags."
authors = ["bubshurb"]
license = "MIT"
version = "1.0.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4"