[package]
name = "bubshurb/playerrefutil"
description = "A simple utility module for retrieving player refs."
authors = ["bubshurb"]
version = "1.0.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
    
[dependencies]
Promise = "evaera/promise@4"
Signal = "sleitnick/signal@2"
playerEventsUtil = "bubshurb/playereventsutil@1"