[package]
name = "bubshurb/matterentityutil"
description = "Utility module for working with matter entities."
authors = ["bubshurb"]
license = "MIT"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4"