[package]
name = "bubshurb/playerhumanoidwalkspeedutil"
description = "A very simple utility module for working with player humanoid walkspeed multipliers."
authors = ["bubshurb"]
version = "1.0.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
instanceAttributeUtil = "bubshurb/instanceattributeutil@1"
playerHumanoidUtil = "bubshurb/playerhumanoidutil@1"